# Generated by Django 5.1.7 on 2025-04-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
